### ISSUE TITLE
some issues when running SigProfilerClusters? 

### ISSUE THREAD

**Issue by YingYa** [AlexandrovLab/SigProfilerClusters#1]
Hi,

I am running SigProfilerClusters, and find some issues:
1. line 223 of SigProfilerSimulator.py:
    log_out.write("Project: {}\n**Genome:** {}\n**Input File Path:** {}\ncontexts: {}\nexome: {}\nsimulations: {}\nupdating: {}\nbed_file: {}\noverlap: {}\ngender: {}\nseqInfo: {}\nchrom_based: {}\nseed_file: {}\n".format(project, **project_path**, **genome**, contexts, str(exome), str(simulations),  str(updating), str(bed_file), str(overlap), gender, str(seqInfo), str(chrom_based), str(seed_file)))

2. line 594 of of SigProfilerSimulator.py:
    sigs.sigProfilerExtractor("table", ref_dir+"output/extraction_clustered/", ref_dir+"output/vcf_files" + path_suffix + "/"+project+"_clustered/SNV/output/SBS/"+project+"_clustered.SBS96.all", genome, **startProcess**=startProcess, **endProcess**=endProcess, totalIterations=totalIterations)#, totalIterations=totalIterations)
	**startProcess** should be minimum_signatures
        **endProcess** should be maximum_signatures

3. chrom_based=Ture but log file of SigProfilerMatrixGenerator says chrom_based=False
    seqInfo=False but log file of SigProfilerMatrixGenerator says seqInfo=True

**Comment by ebergstr** [comment]
Thank you for the feedback! To address the raised issues:

1. We have fixed the typo in the simulator tool. Please manually update that tool to see these changes (pip install SigProfilerSimulator --upgrade).
2. Running extractions directly from the Clusters tool is temporarily deprecated. I have commented out this section of the code to avoid any confusion.
3. The output that you are seeing from the matrixGenerator is the result of the order of operations when running simulations with chrom_based=True. Ultimately, the final iteration of the matrixGenerator called by the simulator actually uses chrom_based=False, which is what you see in the final log file. If you are seeing this issue when running the matrixGenerator individually, please open a new issue under the SigProfilerMatrixGenerator repository.

I will close this comment as resolved; however, please feel free to open additional issues in the respective repositories if any arise.
