### ISSUE TITLE
How to tell the Clusters to use the VAF in MAF input?

### ISSUE THREAD

**Issue by lincj1994** [AlexandrovLab/SigProfilerClusters#13]
Hi. Thanks for developing and maintaing such a cool tool.
I'm wondering how to tell the Clusters to use the VAFs if the input file is in MAF format.
Thanks.
Lin.

**Comment by ebergstr** [comment]
Hi Lin,

The tool will only work with VAFs if the input files are provided in VCF format. Please see the following page on our wiki page for an example of the accepted VCF (with VAFs) format.

https://osf.io/qpmzw/wiki/5.%20Quick%20Start%20Example/

Thanks!
Erik
