### ISSUE TITLE
UnboundLocalError: local variable 'matrix_file_suffix' referenced before assignment

### ISSUE THREAD

**Issue by fonetto** [AlexandrovLab/SigProfilerClusters#14]
Hello! I'm having the following issue when running SigProfilerClusters using the 21BRCA dataset. Using Python 3.9.12 - Conda  Spyder IDE . Would you be able to help? Thanks in advance!

`from SigProfilerClusters import SigProfilerClusters as hp`

`hp.analysis(project="21BRCA_Rv3", genome="GRCh37", contexts=["96"], simContext=["96"], input_path="/Users/fonetto/21BRCA/21BRCA_Rv3/") `

======================================
Beginning SigProfilerClusters Analysis
======================================

Calculating mutational distances...Completed!

### Traceback (most recent call last):

Input In [2] in <cell line: 1>
hp.analysis(project="21BRCA_Rv3", genome="GRCh37", contexts=["96"], simContext=["96"], input_path="/Users/fonetto/21BRCA/21BRCA_Rv3/")

File ~/opt/anaconda3/lib/python3.9/site-packages/SigProfilerClusters/SigProfilerClusters.py:669 in analysis
regions, imds = hotspot.hotSpotAnalysis(project, genome, contexts, simContext, ref_dir, windowSize, processors, plotIMDfigure, exome, chromLengths, binsDensity, original, signature, percentage, firstRun, clustering_vaf, calculateIMD, chrom_based, correction)

File ~/opt/anaconda3/lib/python3.9/site-packages/SigProfilerClusters/hotspot.py:893 in hotSpotAnalysis
matrix_file_suffix_original = matrix_file_suffix + "all"

UnboundLocalError: local variable 'matrix_file_suffix' referenced before assignment

**Comment by MousumyCSE** [comment]
Hi,
Thanks for your comment. During running SigProfilerClusters, you also have to mention the other parameters.

Please try this:
from SigProfilerClusters import SigProfilerClusters as hp
hp.analysis(project="21BRCA_Rv3", genome="GRCh37", contexts="96", simContext=["96"], input_path="/Users/fonetto/21BRCA/21BRCA_Rv3/", analysis="all", sortSims=True, subClassify=True, correction=True, calculateIMD=True, TCGA=True, sanger=False)

Please let me know, if that resolve your issues.

Best,
Mousumy

**Comment by fonetto** [comment]
Hi Mousumy,

Thanks a lot for your help. It did solve the issue. 

Best,
Fred
