### ISSUE TITLE
issue with using CCFs

### ISSUE THREAD

**Issue by timchu90** [AlexandrovLab/SigProfilerClusters#15]
https://github.com/AlexandrovLab/SigProfilerClusters/blob/804a6333bdde8df68241736ec1adba4faaa1adce/SigProfilerClusters/classifyFunctions.py#L112

ran into error where 'vafs' does not exist. should be ccfs[sample][keyLine] = ccf ?

**Comment by MousumyCSE** [comment]
Hi there,

Apologies for the late response.

Can you please let me know what are the commands you are using to run SigProfilerClusters tool?
Also please send the log files and example input file you are using. 

By this time, can I ask you to check if you are using the updated version of the tools or not! If so, please remove the previous log and the output files and rerun the SigProfilerClusters tool.

Best,
Mousumy

**Comment by timchu90** [comment]
```
from SigProfilerMatrixGenerator import install as genInstall
from SigProfilerSimulator import SigProfilerSimulator as sigSim
from SigProfilerClusters import SigProfilerClusters
import sys

SigProfilerClusters.analysis(sys.argv[1], 
    "GRCh38", 
    "96", 
    ["288"], 
    sys.argv[2], 
    analysis="all", 
    sortSims=True, 
    subClassify=True, 
    correction=True, 
    calculateIMD=True, 
    max_cpu = 1,
    TCGA=False, 
    sanger=False,
    standardVC = True,
    includedVAFs=False,
    includedCCFs=True
)
```
Yes, this is on the latest release 1.0.0

**Comment by MousumyCSE** [comment]
Hi,

Can you please share the log files and one of your example files so that I can check at my end! You can mail me at mkundu@health.ucsd.edu.

Best,
Mousumy

**Comment by timchu90** [comment]
Hi Mousumy,

Thanks for looking into this. This really looks to just be a typo. I've already fixed the line on my end and it works fine. Unless there is something I am missing, any command run using the `includedCCF=True` argument will run into this error? 

Thanks again, 
Tim

**Comment by MousumyCSE** [comment]
Hi Tim,
 
Glad to here that it worked at your end.

Yes, you have to run with (includedCCFs=True), otherwise it will show error. Please let me know if there are any further issues.


Best,
Mousumy

**Comment by mdbarnesUCSD** [comment]
Please re-open this issue if you encounter this.
