### ISSUE TITLE
Unable to cluster mutations

### ISSUE THREAD

**Issue by aliahhawari** [AlexandrovLab/SigProfilerClusters#17]
I have been able to run the BRCA test vcf and get the outputs as per /example. I am now trying to run on my vcf but it seems to stop after calclulating mutational distances as the figure below. Do you know why that is? What preprocessing should I do to my vcfs? 

![image](https://github.com/AlexandrovLab/SigProfilerClusters/assets/66627434/a1548252-516f-4934-ae85-12ef9605b7b5)

**Comment by MousumyCSE** [comment]
Hi @aliahhawari,

Thanks for reaching out. Can you please share the log files?

Best,
Mousumy

**Comment by aliahhawari** [comment]
Sure. Thank you for replying. 
![image](https://github.com/AlexandrovLab/SigProfilerClusters/assets/66627434/7d60a1e4-8746-4918-a1dc-178229a8ef14)
![image](https://github.com/AlexandrovLab/SigProfilerClusters/assets/66627434/41bddc2a-1322-4924-964d-a61524577f9c)

**Comment by MousumyCSE** [comment]
Hi @aliahhawari,

Thanks for sharing the log files. Currently, Cluster tool doesn't support for mitochondrial(MT) chromosome. My suggestion will be to remove 'MT' from your input data and re-run the cluster pipeline.

Please let me know if you encounter any other issues.

Best,
Mousumy

**Comment by aliahhawari** [comment]
Hi Mousumy, does that mean that the error above refers that I have 'chrMT' in my CHROM column in my vcf?

**Comment by aliahhawari** [comment]
HI Mousumy, 

Thanks for your reply but I still get errors. I have removed chrM from the input vcf. The clustered and nonclustered folders are not generated and here is the error and output log: 
![image](https://github.com/AlexandrovLab/SigProfilerClusters/assets/66627434/253be40c-7cfe-47b1-b4af-f7326a15994c)

![image](https://github.com/AlexandrovLab/SigProfilerClusters/assets/66627434/728c12b4-ad07-4b3e-a45c-464111404468)

**Comment by MousumyCSE** [comment]
Hi @aliahhawari,

It will be great if you can share one of your example files so that I can run at my end. 

Best,
Mousumy

**Comment by MousumyCSE** [comment]
Hi @aliahhawari,

Please reopen the issue if you encounter any other problems.

Thanks,
Mousumy
