### ISSUE TITLE
'SigProfilerMatrixGenerator.scripts.SigProfilerMatrixGeneratorFunc' has no attribute 'reference_paths'

### ISSUE THREAD

**Issue by christianbosselmann** [AlexandrovLab/SigProfilerClusters#19]
Hi,

I have been following step-by-step. All other parts of the SigProfiler tool suite have worked great - thanks for this fantastic resource. I have however encountered this error:

`hp.analysis("lfe_sim", "GRCh37", "96", "96", "/SigProfiler/files", subClassify=False)`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.10/site-packages/SigProfilerClusters/SigProfilerClusters.py", line 400, in analysis
    chrom_path, ref_dir = matRef.reference_paths(genome)
AttributeError: module 'SigProfilerMatrixGenerator.scripts.SigProfilerMatrixGeneratorFunc' has no attribute 'reference_paths'`

I am unable to figure out the reason for this error. I have previously installed the reference just fine and it worked for matGen.SigProfilerMatrixGenerator.

`>>> genInstall.install('GRCh37', rsync=False, bash=True)
Beginning installation. This may take up to 40 minutes to complete.
The transcriptional reference data for GRCh37 has been saved.
All reference files have been created.
Verifying and benchmarking installation now...
Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 1.16 seconds.
Matrices generated for 1 samples with 0 errors. Total of 2430 SNVs, 0 DINUCs, and 0 INDELs were successfully analyzed.
Installation was succesful.
SigProfilerMatrixGenerator took 6.068857669830322 seconds to complete.
To proceed with matrix_generation, please provide the path to your vcf files and an appropriate output path.
Installation complete.`

I would appreciate any help or insight.

Best wishes

Christian

**Comment by ebergstr** [comment]
Hi Christian,

We are aware of this issue and have fixed this within the newest version of SigProfilerClusters (v1.1.1) and SigProfilerMatrixGenerator. Can I please ask you to upgrade your SigProfilerClusters tool as follows:

pip install SigProfilerClusters --upgrade

This will automatically upgrade SigProfilerMatrixGenerator as well. I will close this issue, but please reopen if you are still experiencing issues.

Best,
Erik
