### ISSUE TITLE
imds_corrected when correction=True and chrom_based=True

### ISSUE THREAD

**Issue by ksoyeona** [AlexandrovLab/SigProfilerClusters#2]
SigProfilerClusters error log 

```
 File "<stdin>", line 1, in <module>
  File "MY_PATH/SigProfilerClusters/SigProfilerClusters.py", line 609, in analysis
    classifyFunctions.findClustersOfClusters_noVAF (project, chrom_based, input_path, windowSize, chromLengths, regions, log_file, genome, processors, imds, correction)
  File "my_path/SigProfilerClusters/classifyFunctions.py", line 844, in findClustersOfClusters_noVAF
    with open(project_parent_path + "output/simulations/data/imds_corrected.pickle", "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'MY_PROJECT_DIR/output/simulations/data/imds_corrected.pickle'
```
Hello,

SigProfilerClusters looks for imds_corrected.pickle while MY_PROJECT_DIR/output/simulations/data/ have imds_chrom.pickle and imds_corrected_chrom.pickle. 

i set `correction=True` and `chrom_based=True` in SigProfilerClusters. shouldn't SigProfilerClusters look for `imds_corrected_chrom.pickle` instead of `imds_corrected.pickle` when both `correction=True and chrom_based=True`? 

Below are the lines of code I used. 
```
sigSim.SigProfilerSimulator("PROJECT_NAME", "MY_PATH", "GRCh37", contexts = ['1536'], chrom_based=True, simulations=100)

hp.analysis("PROJECT_NAME", "GRCh37", "96", ["1536"], "MY_PATH", analysis="all", sortSims=True, subClassify=True, correction=True, calculateIMD=True, chrom_based=True, includedVAFs=False, plotIMDfigure=True, plotRainfall=True, windowSize=1000000)

```
Thanks in advance.

**Comment by ebergstr** [comment]
Hi,

Thank you for bringing this issue to our attention!

Actually, the chrom_based parameter within the cluster pipeline is not necessary and has now been deprecated to avoid future confusion. You should be able to run the same set of commands with chrom_based=False. For example, if you perform simulations with chrom_based=True, these simulations will automatically be used within SigProfilerClusters without needing to set that parameter within the SigProfilerClusters command. 

I am closing this issue; however, please feel free to reopen or open a new issue. Likewise, please feel free to email ebergstr@eng.ucsd.edu if you have additional questions.
