### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by cutleraging** [AlexandrovLab/SigProfilerClusters#21]
Hello, I am having the following issue with installing this package in my environment

`$ pip install SigProfilerClusters
Collecting SigProfilerClusters
  Downloading SigProfilerClusters-1.1.2-py3-none-any.whl.metadata (11 kB)
Collecting matplotlib<3.5,>=3.3.0 (from SigProfilerClusters)
  Downloading matplotlib-3.4.3.tar.gz (37.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 49.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-q90iz707/matplotlib_e257a3b3ba18440caedc4fb8265f9362/setup.py", line 54, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-q90iz707/matplotlib_e257a3b3ba18440caedc4fb8265f9362/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-q90iz707/matplotlib_e257a3b3ba18440caedc4fb8265f9362/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-q90iz707/matplotlib_e257a3b3ba18440caedc4fb8265f9362/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

Thanks,
Ronnie

**Comment by MousumyCSE** [comment]
Hi @cutleragin,

Thanks for reaching out. Can I ask you which version of python you are using?
We are working on updating python version. For now the suggestion will be to use python 3.8 or 3.9  and then retry to install the SigProfilerClusters tool.

Please let me know if you encounter any other issues.

Best,
Mousumy

**Comment by cutleraging** [comment]
Thanks, this worked for me.
