### ISSUE TITLE
plot rainfall error

### ISSUE THREAD

**Issue by temizna** [AlexandrovLab/SigProfilerClusters#25]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/3.10/lib/python/site-packages/SigProfilerClusters/SigProfilerClusters.py", line 706, in analysis
    plottingFunctions.rainfall(chrom_based, project, input_path, chrom_path, chromLengths, centromeres, contexts, includedVAFs, includedCCFs, correction, windowSize, bedRanges)
  File "/Library/Python/3.10/lib/python/site-packages/SigProfilerClusters/plottingFunctions.py", line 1182, in rainfall
    for sample in sorted(samplesSet, key=natural_sortkey):
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by temizna** [comment]
-------Python and Package Versions------- 
Python Version: 3.10.8
SigProfilerMatrixGenerator Version: 1.2.14
SigProfilerPlotting version: 1.3.12
matplotlib version: 3.4.3
scipy version: 1.9.3
numpy version: 1.23.4

**Comment by MousumyCSE** [comment]
Hi @temizna,

Thanks for reaching out!
I did run SigProfilerClusters pipeline with one of the example file and it has run successfully. It will be great if you can share one of your input files so that I can run at my end.

Best,
Mousumy

**Comment by temizna** [comment]
-------Python and Package Versions-------
Python Version: 3.10.8
SigProfilerMatrixGenerator Version: 1.2.14
SigProfilerPlotting version: 1.3.12
matplotlib version: 3.4.3
scipy version: 1.9.3
numpy version: 1.23.4

 43_Liver_tumor_2.mut.dna.pass.ad3.dp10.vaf0.05.vcf
<https://drive.google.com/file/d/1yqyqOlvgioQGSZe73Lt0M4T0196xXIAO/view?usp=drive_web>
 78_liver_tumor.mut.dna.pass.ad3.dp10.vaf0.05.vcf
<https://drive.google.com/file/d/11IJ4pizAZzL-yF76wgRbNoVuIld-JTWX/view?usp=drive_web>
 131_renal_node_1.mut.dna.pass.ad3.dp10.vaf0.05.vcf
<https://drive.google.com/file/d/1UwM3iq1jd5nABSdsqwlU7zJu7bs71q9n/view?usp=drive_web>
 CD_4NQO_178_tumor_S26.mut.dna.pass.ad3.dp10.vaf0.05.vcf
<https://drive.google.com/file/d/1J6Q67tlgau7_0beryJVLZgjTfZz82KOs/view?usp=drive_web>
 CD_4NQO_247_tumor_S28.mut.dna.pass.ad3.dp10.vaf0.05.vcf
<https://drive.google.com/file/d/1D2PkHkovdJyOPgC83lpOvujC0EGBKvro/view?usp=drive_web>

**Comment by MousumyCSE** [comment]
Hi @temizna,

Thank you for sending!

Could you please let me know how you are running the cluster pipeline? Additionally please share the log files(.err and .out file). By this time my suggestion will be to create a new conda environment and re-install the tools and run it again.

Best,
Mousumy

**Comment by temizna** [comment]
How do you create a new conda environment for the tools? I did not see an
option like that on the github pages.
I used pip to install these

A

**Comment by MousumyCSE** [comment]
Hi @temizna,

I hope you have installed Anaconda or Miniconda in your computer. If you haven't installed Anaconda or Miniconda yet, you can download and install it from their respective websites.

Then create a new conda Environment with Python 3.10. Please see below how you can create an environment:
# Create a new environment with Python 3.10
conda create --name myenv python=3.10

# Activate the new environment
conda activate myenv

Next, you can re-install the tools using pip (for example: pip install SigProfilerClusters). Please follow wiki page(https://osf.io/qpmzw/wiki/home/) to install the required genome. 

Hope that was helpful. Please let me know which genome you are using(GRCh37 or GRCh38) to run the SigProfilerClusters tool?

Best,
Mousumy

**Comment by temizna** [comment]
I have python 3.11. Do you think that is causing the issue?
I use grch38 and mm10 for human and mouse.

**Comment by MousumyCSE** [comment]
I am guessing, it's not a python version issue. 
You sent me the python and package versions where it looks you are using Python 3.10.8. However, we have checked with Python 3.11 and it works if you run the SigProfilerClusters tool within python script by defining the main function(please see this issue: https://github.com/AlexandrovLab/SigProfilerClusters/issues/23). 
 
I hope the example files you have shared with me, all are human(GRCh38) sample. Please let me know if I am not correct.



> -------Python and Package Versions------- Python Version: 3.10.8 SigProfilerMatrixGenerator Version: 1.2.14 SigProfilerPlotting version: 1.3.12 matplotlib version: 3.4.3 scipy version: 1.9.3 numpy version: 1.23.4

I

**Comment by temizna** [comment]
mm10

**Comment by temizna** [comment]
I followed your advice and I am still getting the same plot rainfall error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/Users/temizna/Library/Python/3.10/lib/python/site-packages/SigProfilerClusters/SigProfilerClusters.py",
line 706, in analysis
    plottingFunctions.rainfall(chrom_based, project, input_path,
chrom_path, chromLengths, centromeres, contexts, includedVAFs,
includedCCFs, correction, windowSize, bedRanges)
  File
"/Users/temizna/Library/Python/3.10/lib/python/site-packages/SigProfilerClusters/plottingFunctions.py",
line 1182, in rainfall
    for sample in sorted(samplesSet, key=natural_sortkey):
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by MousumyCSE** [comment]
HI @temizna,

Sorry to hear that.
I ran the SigProfilerClusters pipeline with one of your example file and it works at my end(please see the attached
[rainfallPlots_clustered_test_corrected.pdf](https://github.com/user-attachments/files/16018755/rainfallPlots_clustered_test_corrected.pdf)
).

This is how I am running the pipeline:
from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
matrices = matGen.SigProfilerMatrixGeneratorFunc("test", "mm10", "/Desktop/SigProfilerIssues/SPC_rainfall_plot_issue/",plot=True, exome=False, bed_file=None, chrom_based=False, tsb_stat=False, seqInfo=False, cushion=100)

from SigProfilerSimulator import SigProfilerSimulator as sigSim
sigSim.SigProfilerSimulator("test", "/Desktop/SigProfilerIssues/SPC_rainfall_plot_issue/", "mm10", contexts=['96'], simulations=100, chrom_based=False, exome=False, vcf=False, cushion=100)

from SigProfilerClusters import SigProfilerClusters as hp
hp.analysis("test", "mm10", "96", ["96"], "/Desktop/SigProfilerIssues/SPC_rainfall_plot_issue/", analysis="all", sortSims=True, subClassify=True, correction=True, calculateIMD=True, includedVAFs=False, includedCCFs=False, exome=False)

Can I please ask you to update the packages according to the versions that I am using:
-------Python and Package Versions------- 
Python Version: 3.10.14
SigProfilerMatrixGenerator Version: 1.2.26
SigProfilerPlotting version: 1.3.23
matplotlib version: 3.4.3
scipy version: 1.10.1
numpy version: 1.23.5

Hope that will solve your issues. Please let me know if you have any questions.

Best,
Mousumy

**Comment by temizna** [comment]
I am getting a sigplofilerplotting error and also scypy error:

temizna$ pip install --force-reinstall -v "SipProfilerPlotting==1.3.23"

Using pip 24.0 from
/Users/temizna/anaconda3/envs/sigprofiler/lib/python3.10/site-packages/pip
(python 3.10)

ERROR: Could not find a version that satisfies the requirement
SipProfilerPlotting==1.3.23 (from versions: none)

ERROR: No matching distribution found for SipProfilerPlotting==1.3.23


sigprofilermatrixgenerator 1.2.26 requires scipy>=1.12.0; python_version >=
"3.9", but you have scipy 1.10.1 which is incompatible.

**Comment by MousumyCSE** [comment]
Hi @temizna,

Please create a new environment using conda and re-install the tools. Here are the commands below:

# Create a new environment
conda create -n SPC_new python=3.10
conda activate SPC_new

# Install compatible versions of numpy, pandas, and scipy
conda install numpy=1.23.5 pandas=1.5.3 scipy=1.12.0

#install the tool
pip install SigProfilerClusters

Please run the SigProfilerClusters pipeline again and let me know if that works at your end.

Best,
Mousumy

**Comment by temizna** [comment]
did all that
still getting the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/Users/temizna/Library/Python/3.10/lib/python/site-packages/SigProfilerClusters/SigProfilerClusters.py",
line 706, in analysis
    plottingFunctions.rainfall(chrom_based, project, input_path,
chrom_path, chromLengths, centromeres, contexts, includedVAFs,
includedCCFs, correction, windowSize, bedRanges)
  File
"/Users/temizna/Library/Python/3.10/lib/python/site-packages/SigProfilerClusters/plottingFunctions.py",
line 1182, in rainfall
    for sample in sorted(samplesSet, key=natural_sortkey):
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by MousumyCSE** [comment]
Hi @temizna,

Sorry to hear that!
It's hard to figure out why it is not working at your end. May be we can set up a quick Zoom call this week or early next week if that works for you. 

Best,
Mousumy

**Comment by temizna** [comment]
I can meet Tuesday July 9 in the afternoon central time. I am free from 1
pm central till 5 pm central.

Thanks.

Alpay

**Comment by MousumyCSE** [comment]
Thank you for letting me know. Could you please share your email address! 

Best,
Mousumy

**Comment by temizna** [comment]
***@***.***

**Comment by MousumyCSE** [comment]
Sorry, but your email address is not readable to me. It will be great if you could send an email at mkundu@health.ucsd.edu. 

Best,
Mousumy

**Comment by Trueway-X** [comment]
Dont know whether this issue solved or not, but according to my reply in the other issue (https://github.com/AlexandrovLab/SigProfilerClusters/issues/27#issuecomment-2289608845), it might be you are tring to use contexts=["96"] as input. Using contexts="96" may help.

**Comment by temizna** [comment]
I will try that. Thanks.

**Comment by MousumyCSE** [comment]
Hi @temizna,

We have updated the SigProfilerClusters tools to v1.1.3. Please open a new conda environment and re-install the updated tools and run your input files through the cluster pipeline. If you encounter any issues, please send me your log files.

Best,
Mousumy

**Comment by temizna** [comment]
This is the error I am getting now with simulator and there are no error
log files

>>> from SigProfilerSimulator import SigProfilerSimulator as sigSim

>>> sigSim.SigProfilerSimulator("cag_nqo_clusters",
"/Users/temizna/Google_Drive/UMN/HARRIS/CAM_TUMORS/DNA/cag_4nqo/4-callers/four-caller-vcfs/vcfs/",
"mm10", contexts="288", simulations=100, chrom_based=True)


======================================

        SigProfilerSimulator

======================================


Checking for all reference files and relevant matrices...

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File
"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/SigProfilerSimulator/SigProfilerSimulator.py",
line 144, in SigProfilerSimulator

    contexts.sort(reverse=True)

AttributeError: 'str' object has no attribute 'sort'

>>>

**Comment by MousumyCSE** [comment]
Hi @temizna,

Thanks for letting me know!

When you run the SigProfilerSimulator, you need to specify the contexts as a list(ex: contexts=["288"]). Please see the below code to run the SigProfilerSimulator tool:

>> from SigProfilerSimulator import SigProfilerSimulator as sigSim
>> sigSim.SigProfilerSimulator("cag_nqo_clusters", "/Users/temizna/Google_Drive/UMN/HARRIS/CAM_TUMORS/DNA/cag_4nqo/4-callers/four-caller-vcfs/vcfs/", "mm10", contexts=["96"], simulations=100, chrom_based=True)

Let me know if you have any further issues.

Best,
Mousumy

**Comment by temizna** [comment]
Okay. This worked and rainfall plots worked with this version!

Thanks to you all!

Alpay

**Comment by MousumyCSE** [comment]
Hi @temizna,

Thank you for letting us know! Glad that it's working at your end. If you encounter any other problems, please re-open this issue.

Best,
Mousumy
