### ISSUE TITLE
How to set parameters to run SigProfilerClusters for INDEL?

### ISSUE THREAD

**Issue by YingYa** [AlexandrovLab/SigProfilerClusters#3]
Hi,

I am running SigProfilerClusters for INDEL data with the following parameters:
genome=GRCh38, contexts=ID, simContext=ID, interdistance=ID, analysis=all, sortSims=True, subClassify=True, correction=True, calculateIMD=True, max_cpu=32, sanger=False, TCGA=True, simulations=100

The job is running SigProfilerSimulator step now, but it took more than 1 hour to finish simulation for each sample. My project have hundreds of samples that may take more than one month to run.

How could I speed up the SigProfilerClusters for INDEL?

Best

**Comment by ebergstr** [comment]
Hi,

Can you provide additional information on your project (i.e. average number of indels per sample)? Can you also provide the list of parameters that you are using to run the simulator? 

Best

**Comment by YingYa** [comment]
Hi,

Average number of indels per sample is about 36000 (from 50 to 345000).

Parameters for simulator:
sigSim.SigProfilerSimulator(project=project, project_path=project_path, genome=GRCh38, contexts=ID, exome=False, simulations=100,
        updating=False, bed_file=None, overlap=False, gender=female, seqInfo=False, chrom_based=True, seed_file=None,
        spacing=1, noisePoisson=False, noiseUniform=0, cushion=100, region=None, vcf=False, mask=None)

Best

**Comment by ebergstr** [comment]
Hi,

We have not benchmarked against samples with this high of indel TMB, so the simulator is likely struggling to complete many of the high TMB samples. Within PCAWG, we have on average ~1,400 indels per sample with maximum of ~137,000, which should run through without any problems. However, if you also have a large number of samples, I would recommend batching your project into multiple jobs. With projects containing more than 500 samples, we typically simulate across batches to manually speed up the process. 

Best

**Comment by YingYa** [comment]
Hi, 

Thanks for your suggestion.

You mean I could batching my project into multiple simulator jobs firstly, then run cluster separately or use the merged simulator results to run cluster? 

Best

**Comment by ebergstr** [comment]
Correct, we typically:
    1) Separate the samples into smaller project sizes.
    2) Run simulator on each batch
    3) Run clusters on each batch.

This should help speed up the process and/or locate problematic samples easier.

Best
