### ISSUE TITLE
column to extract VAF when standardVC

### ISSUE THREAD

**Issue by ksoyeona** [AlexandrovLab/SigProfilerClusters#4]
Hello,

on the SigProfilerClusters Wiki page, there seems to be an inconsistency in the documentation.

> If your VAF is recorded in the **8th** column of your VCF as AF=xx, set standardVC=True, TCGA=False, and sanger=False.

the above states that `standardVC=True` when VAF is in the **8th** while the below says that `standardVC=True` when VAF is in the **7th** column.

> Parameter | Variable Type | Description
> standardVC | Boolean | Parameter that informs the tool of what format the VAF scores are provided. This is required when subClassify=True and sanger=False and TCGA=False and when the data contains VAF formatted in the **7th** column as AF=XX (default=False)

yet, in classifyFunctions.py, `vaf = float(lines[9].split("AF=")[1].split(";")[0])`  vaf seems to be extracted from the 10th column.
i'd appreaciate it if you could clarify this issue.

Thanks a lot!

```
elif standardVC:
		vafs = {}
		for vcfFile in vcf_files:
			sample = vcfFile.split(".")[0]
			vafs[sample] = {}
			with open(vcf_path + vcfFile) as f:
				for lines in f:
					if lines[0] == "#":
						continue
					lines = lines.strip().split()
					chrom = lines[0]
					pos = lines[1]
					ref = lines[3]
					alt = lines[4]
					try:
						vaf = float(lines[9].split("AF=")[1].split(";")[0])
					except:
						vaf = -1.5
					keyLine = ":".join([chrom, pos, ref, alt])
					vafs[sample][keyLine] = vaf
```

**Comment by ebergstr** [comment]
Hi,

Thank you for your feedback. Indeed, this was an inconsistency, which has now been fixed in the OSF and function doc strings. The proper format should contain VAFs in the 10th column when using standardVC=True.

This should resolve the issue; however, please feel free to reopen or start a new issue if necessary.

Best.
